module-3/03-Introduction-to-MVC-Views/lecture-final/dotnet/TechElevator.Web/Controllers/CalculatorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TechElevator.Web.Controllers
{
    public class CalculatorsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

module-3/03-Introduction-to-MVC-Views/lecture-final/dotnet/TechElevator.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TechElevator.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Greeting()
        {
            return View();
        }
    }
}

module-3/03-Introduction-to-MVC-Views/lecture-final/dotnet/TechElevator.Web/Views/Calculators/Index.cshtml
@{
    ViewData["Title"] = "Metric to Imperial";
}

<h2>Metric to Imperial</h2>


<table>
    <thead>
        <tr>
            <th>Metric Unit</th>
            <th>Imperial Unit</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i <= 1000; i += 15)
        {
            <tr>
                <td>@i km/h</td>
                <td>@((int)(i * 0.62)) mph</td>
            </tr>
        }
    </tbody>

</table>

module-3/03-Introduction-to-MVC-Views/lecture-final/dotnet/TechElevator.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>    
    <nav>
        <ul>
            <li><a asp-controller="Home" asp-action="Index">Index</a></li>
            <li><a asp-controller="Home" asp-action="Greeting">Greeting</a></li>
            <li><a asp-controller="Calculators" asp-action="Index">Metric/Imperial Calculator</a></li>
        </ul>
    </nav>

    @RenderBody()
</body>
</html>